/* 
 * Sentech Camera Driver for Linux
 * 
 * Copyright (C) 2017 Omron Sentech CO.,LTD
 * 
 */

#ifndef __STCAM_DD_H__
#define __STCAM_DD_H__

#include <linux/videodev2.h>

// Sentech original control id
#define STC_CID_COLOR_ARRAY							V4L2_CID_PRIVATE_BASE + 0
#define STC_CID_TRANSFER_BITS_PER_PIXEL				V4L2_CID_PRIVATE_BASE + 1
#define STC_CID_TEMPERATURE							V4L2_CID_PRIVATE_BASE + 2
#define STC_CID_RESET_COUNTER						V4L2_CID_PRIVATE_BASE + 3
#define STC_CID_CAMERA_SETTING						V4L2_CID_PRIVATE_BASE + 4
#define STC_CID_SCAN_MODE							V4L2_CID_PRIVATE_BASE + 5
#define STC_CID_MAX_ROI_COUNT						V4L2_CID_PRIVATE_BASE + 6
#define STC_CID_V_DECIMATION_BINNING				V4L2_CID_PRIVATE_BASE + 7
#define STC_CID_H_DECIMATION_BINNING				V4L2_CID_PRIVATE_BASE + 8
#define STC_CID_BINNINGSUM_MODE						V4L2_CID_PRIVATE_BASE + 9
#define STC_CID_OUTPUT_FPS							V4L2_CID_PRIVATE_BASE + 10
#define STC_CID_CLOCK								V4L2_CID_PRIVATE_BASE + 11
#define STC_CID_V_BLANK								V4L2_CID_PRIVATE_BASE + 12
#define STC_CID_MAX_SHORT_EXPOSURE					V4L2_CID_PRIVATE_BASE + 13
#define STC_CID_DIGITAL_GAIN						V4L2_CID_PRIVATE_BASE + 14
#define STC_CID_EXPOSURE_MODE						V4L2_CID_PRIVATE_BASE + 15
#define STC_CID_SENSOR_SHUTTER_MODE					V4L2_CID_PRIVATE_BASE + 16
#define STC_CID_ALC_MODE							V4L2_CID_PRIVATE_BASE + 17
#define STC_CID_ALC_TARGET_LEVEL					V4L2_CID_PRIVATE_BASE + 18
#define STC_CID_AGC_MIN_GAIN						V4L2_CID_PRIVATE_BASE + 19
#define STC_CID_AGC_MAX_GAIN						V4L2_CID_PRIVATE_BASE + 20
#define STC_CID_AE_MIN_EXPOSURE_CLOCK				V4L2_CID_PRIVATE_BASE + 21
#define STC_CID_AE_MAX_EXPOSURE_CLOCK				V4L2_CID_PRIVATE_BASE + 22
#define STC_CID_FRAME_START_TRIGGER_MODE			V4L2_CID_PRIVATE_BASE + 23
#define STC_CID_FRAME_START_TRIGGER_SOURCE			V4L2_CID_PRIVATE_BASE + 24
#define STC_CID_FRAME_START_TRIGGER_DELAY			V4L2_CID_PRIVATE_BASE + 25
#define STC_CID_FRAME_START_TRIGGER_OVERLAP			V4L2_CID_PRIVATE_BASE + 26
#define STC_CID_FRAME_BURST_START_TRIGGER_MODE		V4L2_CID_PRIVATE_BASE + 27
#define STC_CID_FRAME_BURST_START_TRIGGER_SOURCE	V4L2_CID_PRIVATE_BASE + 28
#define STC_CID_FRAME_BURST_START_TRIGGER_DELAY		V4L2_CID_PRIVATE_BASE + 29
#define STC_CID_FRAME_BURST_START_TRIGGER_OVERLAP	V4L2_CID_PRIVATE_BASE + 30
#define STC_CID_EXPOSURE_START_TRIGGER_MODE			V4L2_CID_PRIVATE_BASE + 31
#define STC_CID_EXPOSURE_START_TRIGGER_SOURCE		V4L2_CID_PRIVATE_BASE + 32
#define STC_CID_EXPOSURE_START_TRIGGER_DELAY		V4L2_CID_PRIVATE_BASE + 33
#define STC_CID_EXPOSURE_START_TRIGGER_OVERLAP		V4L2_CID_PRIVATE_BASE + 34
#define STC_CID_EXPOSURE_END_TRIGGER_MODE			V4L2_CID_PRIVATE_BASE + 35
#define STC_CID_EXPOSURE_END_TRIGGER_SOURCE			V4L2_CID_PRIVATE_BASE + 36
#define STC_CID_EXPOSURE_END_TRIGGER_DELAY			V4L2_CID_PRIVATE_BASE + 37
#define STC_CID_EXPOSURE_END_TRIGGER_OVERLAP		V4L2_CID_PRIVATE_BASE + 38
#define STC_CID_READ_OUT_START_TRIGGER_MODE			V4L2_CID_PRIVATE_BASE + 39
#define STC_CID_READ_OUT_START_TRIGGER_SOURCE		V4L2_CID_PRIVATE_BASE + 40
#define STC_CID_READ_OUT_START_TRIGGER_DELAY		V4L2_CID_PRIVATE_BASE + 41
#define STC_CID_READ_OUT_START_TRIGGER_OVERLAP		V4L2_CID_PRIVATE_BASE + 42
#define STC_CID_TRIGGER_SOFTWARE					V4L2_CID_PRIVATE_BASE + 43
#define STC_CID_TRIGGER_WAIT_HD						V4L2_CID_PRIVATE_BASE + 44
#define STC_CID_TRIGGER_WAIT_READOUT				V4L2_CID_PRIVATE_BASE + 45
#define STC_CID_EXPOSURE_DELAY						V4L2_CID_PRIVATE_BASE + 46
#define STC_CID_STROBE_START_DELAY					V4L2_CID_PRIVATE_BASE + 47
#define STC_CID_STROBE_END_DELAY					V4L2_CID_PRIVATE_BASE + 48
#define STC_CID_OUTPUT_PULSE_DELAY					V4L2_CID_PRIVATE_BASE + 49
#define STC_CID_OUTPUT_PULSE_DURATION				V4L2_CID_PRIVATE_BASE + 50
#define STC_CID_READOUT_DELAY						V4L2_CID_PRIVATE_BASE + 51
#define STC_CID_LINE_DEBOUNCE_TIME					V4L2_CID_PRIVATE_BASE + 52
#define STC_CID_IO0_DIRECTION						V4L2_CID_PRIVATE_BASE + 53
#define STC_CID_IO0_POLARITY						V4L2_CID_PRIVATE_BASE + 54
#define STC_CID_IO0_MODE							V4L2_CID_PRIVATE_BASE + 55
#define STC_CID_IO0_STATUS							V4L2_CID_PRIVATE_BASE + 56
#define STC_CID_IO1_DIRECTION						V4L2_CID_PRIVATE_BASE + 57
#define STC_CID_IO1_POLARITY						V4L2_CID_PRIVATE_BASE + 58
#define STC_CID_IO1_MODE							V4L2_CID_PRIVATE_BASE + 59
#define STC_CID_IO1_STATUS							V4L2_CID_PRIVATE_BASE + 60
#define STC_CID_IO2_DIRECTION						V4L2_CID_PRIVATE_BASE + 61
#define STC_CID_IO2_POLARITY						V4L2_CID_PRIVATE_BASE + 62
#define STC_CID_IO2_MODE							V4L2_CID_PRIVATE_BASE + 63
#define STC_CID_IO2_STATUS							V4L2_CID_PRIVATE_BASE + 64
#define STC_CID_IO3_DIRECTION						V4L2_CID_PRIVATE_BASE + 65
#define STC_CID_IO3_POLARITY						V4L2_CID_PRIVATE_BASE + 66
#define STC_CID_IO3_MODE							V4L2_CID_PRIVATE_BASE + 67
#define STC_CID_IO3_STATUS							V4L2_CID_PRIVATE_BASE + 68
#define STC_CID_LED_STATUS							V4L2_CID_PRIVATE_BASE + 69
#define STC_CID_RESET_SWITCH						V4L2_CID_PRIVATE_BASE + 70
#define STC_CID_SW_STATUS							V4L2_CID_PRIVATE_BASE + 71
#define STC_CID_TIMEOUT_ST2EE						V4L2_CID_PRIVATE_BASE + 72
#define STC_CID_TIMEOUT_TE2EE						V4L2_CID_PRIVATE_BASE + 73
#define STC_CID_TIMEOUT_EE2TE						V4L2_CID_PRIVATE_BASE + 74
#define STC_CID_TIMEOUT_RO2TE						V4L2_CID_PRIVATE_BASE + 75
#define STC_CID_EXPOSURE_END_CALLBACK				V4L2_CID_PRIVATE_BASE + 76
#define STC_CID_TRANSFER_END_CALLBACK				V4L2_CID_PRIVATE_BASE + 77
#define STC_CID_RCV_ERROR_CALLBACK					V4L2_CID_PRIVATE_BASE + 78
#define STC_CID_HDR_TYPE							V4L2_CID_PRIVATE_BASE + 79
#define STC_CID_WHITE_BALANCE_MODE					V4L2_CID_PRIVATE_BASE + 80
#define STC_CID_WHITE_BALANCE_GAIN_R				V4L2_CID_PRIVATE_BASE + 81
#define STC_CID_WHITE_BALANCE_GAIN_GR				V4L2_CID_PRIVATE_BASE + 82
#define STC_CID_WHITE_BALANCE_GAIN_GB				V4L2_CID_PRIVATE_BASE + 83
#define STC_CID_WHITE_BALANCE_GAIN_B				V4L2_CID_PRIVATE_BASE + 84
#define STC_CID_CAMERA_GAMMA						V4L2_CID_PRIVATE_BASE + 85
#define STC_CID_DEFECT_PIXEL_CORRECTION_COUNT		V4L2_CID_PRIVATE_BASE + 86
#define STC_CID_DEFECT_PIXEL_CORRECTION_MODE		V4L2_CID_PRIVATE_BASE + 87
#define STC_CID_DIGITAL_CLAMP						V4L2_CID_PRIVATE_BASE + 88
#define STC_CID_ANALOG_BLACK_LEVEL					V4L2_CID_PRIVATE_BASE + 89
#define STC_CID_ADJUSTMENT_MODE						V4L2_CID_PRIVATE_BASE + 90
#define STC_CID_CLEAR_BUFFER						V4L2_CID_PRIVATE_BASE + 91

// control menu define
#define STC_MENU_COLOR_ARRAY_MONO		0x0001
#define STC_MENU_COLOR_ARRAY_RGGB		0x0002
#define STC_MENU_COLOR_ARRAY_GRBG		0x0003
#define STC_MENU_COLOR_ARRAY_GBRG		0x0004
#define STC_MENU_COLOR_ARRAY_BGGR		0x0005

#define STC_MENU_CAMERA_SETTING_INITIALIZE			0
#define STC_MENU_CAMERA_SETTING_STANDARD_READ		1
#define STC_MENU_CAMERA_SETTING_STANDARD_WRITE		2
#define STC_MENU_CAMERA_SETTING_DEF_PIX_POS_READ	3
#define STC_MENU_CAMERA_SETTING_DEF_PIX_POS_WRITE	4

#define STC_MENU_SCAN_MODE_NORMAL						0
#define STC_MENU_SCAN_MODE_PARTIAL_1					1
#define STC_MENU_SCAN_MODE_PARTIAL_2					2
#define STC_MENU_SCAN_MODE_PARTIAL_4					3
#define STC_MENU_SCAN_MODE_VARIABLE_PARTIAL				4
#define STC_MENU_SCAN_MODE_BINNING						5
#define STC_MENU_SCAN_MODE_BINNING_PARTIAL_1			6
#define STC_MENU_SCAN_MODE_BINNING_PARTIAL_2			7
#define STC_MENU_SCAN_MODE_BINNING_PARTIAL_4			8
#define STC_MENU_SCAN_MODE_BINNING_VARIABLE_PARTIAL		9
#define STC_MENU_SCAN_MODE_ROI							10

#define STC_MENU_DECIMATION_BINNING_0_0		0
#define STC_MENU_DECIMATION_BINNING_1_0		1
#define STC_MENU_DECIMATION_BINNING_1_1		2
#define STC_MENU_DECIMATION_BINNING_1_2		3
#define STC_MENU_DECIMATION_BINNING_1_4		4
#define STC_MENU_DECIMATION_BINNING_2_0		5
#define STC_MENU_DECIMATION_BINNING_2_1		6
#define STC_MENU_DECIMATION_BINNING_2_2		7
#define STC_MENU_DECIMATION_BINNING_3_0		8
#define STC_MENU_DECIMATION_BINNING_3_1		9
#define STC_MENU_DECIMATION_BINNING_3_3		10
#define STC_MENU_DECIMATION_BINNING_4_0		11
#define STC_MENU_DECIMATION_BINNING_4_1		12
#define STC_MENU_DECIMATION_BINNING_4_2		13
#define STC_MENU_DECIMATION_BINNING_5_0		14
#define STC_MENU_DECIMATION_BINNING_5_1		15
#define STC_MENU_DECIMATION_BINNING_6_0		16
#define STC_MENU_DECIMATION_BINNING_7_0		17
#define STC_MENU_DECIMATION_BINNING_7_1		18
#define STC_MENU_DECIMATION_BINNING_7_3		19

#define STC_MENU_BINNINGSUM_MODE_OFF		0
#define STC_MENU_BINNINGSUM_MODE_H_ON		1
#define STC_MENU_BINNINGSUM_MODE_V_ON		2

#define STC_MENU_CLOCK_NORMAL		0
#define STC_MENU_CLOCK_DIV_2		1
#define STC_MENU_CLOCK_DIV_4		2
#define STC_MENU_CLOCK_VGA_90FPS	3

#define STC_MENU_EXPOSURE_MODE_OFF					0
#define STC_MENU_EXPOSURE_MODE_TIMED				1
#define STC_MENU_EXPOSURE_MODE_TRIGGER_WIDTH		2
#define STC_MENU_EXPOSURE_MODE_TRIGGER_CONTROLLED	3

#define STC_MENU_SENSOR_SHUTTER_MODE_ROLLING		0
#define STC_MENU_SENSOR_SHUTTER_MODE_GLOBAL_RESET	1
#define STC_MENU_SENSOR_SHUTTER_MODE_GLOBAL			2

#define STC_MENU_ALC_MODE_OFF			0
#define STC_MENU_ALC_MODE_AE_ON			1
#define STC_MENU_ALC_MODE_AGC_ON		2
#define STC_MENU_ALC_MODE_AE_AGC_ON		3

#define STC_MENU_TRIGGER_SOURCE_DISABLED	0
#define STC_MENU_TRIGGER_SOURCE_SOFTWARE	1
#define STC_MENU_TRIGGER_SOURCE_HARDWARE	2
#define STC_MENU_TRIGGER_SOURCE_LINE0		2
#define STC_MENU_TRIGGER_SOURCE_LINE1		3
#define STC_MENU_TRIGGER_SOURCE_LINE2		4
#define STC_MENU_TRIGGER_SOURCE_LINE3		5

#define STC_MENU_TRIGGER_OVERLAP_OFF				0
#define STC_MENU_TRIGGER_OVERLAP_READ_OUT			1
#define STC_MENU_TRIGGER_OVERLAP_PREVIOUS_FRAME		2

#define STC_MENU_TRIGGER_SOFTWARE_FRAME_START			0
#define STC_MENU_TRIGGER_SOFTWARE_FRAME_BURST_START		1
#define STC_MENU_TRIGGER_SOFTWARE_EXPOSURE_START		2
#define STC_MENU_TRIGGER_SOFTWARE_EXPOSURE_END			3
#define STC_MENU_TRIGGER_SOFTWARE_READ_OUT_START		4

#define STC_MENU_IO_DIRECTION_INPUT		0
#define STC_MENU_IO_DIRECTION_OUTPUT	1

#define STC_MENU_IO_POLARITY_POSI		0
#define STC_MENU_IO_POLARITY_NEGA		1

#define STC_MENU_IO_MODE_OUT_DISABLE						0
#define STC_MENU_IO_MODE_OUT_GENERAL_OUTPUT					1
#define STC_MENU_IO_MODE_OUT_TRIGGER_OUTPUT_PROGRAMMABLE	2
#define STC_MENU_IO_MODE_OUT_TRIGGER_OUTPUT_LOOP_THROUGH	3
#define STC_MENU_IO_MODE_OUT_EXPOSURE_END					4
#define STC_MENU_IO_MODE_OUT_CCD_READ_END_OUTPUT			5
#define STC_MENU_IO_MODE_OUT_STROBE_OUTPUT_PROGRAMMABLE		6
#define STC_MENU_IO_MODE_OUT_STROBE_OUTPUT_EXPOSURE			7
#define STC_MENU_IO_MODE_OUT_TRIGGER_VALID_OUT				8
#define STC_MENU_IO_MODE_OUT_TRANSFER_END					9
#define STC_MENU_IO_MODE_IN_DISABLE							10
#define STC_MENU_IO_MODE_IN_GENERAL_INPUT					11
#define STC_MENU_IO_MODE_IN_TRIGGER_INPUT					12
#define STC_MENU_IO_MODE_IN_READOUT_INPUT					13
#define STC_MENU_IO_MODE_IN_SUB_TRIGGER_INPUT				14

#define STC_MENU_IO_STATUS_LOW		0
#define STC_MENU_IO_STATUS_HIGH		1

#define STC_MENU_LED_STATUS_OFF				0
#define STC_MENU_LED_STATUS_GREEN_ON		1
#define STC_MENU_LED_STATUS_RED_ON			2
#define STC_MENU_LED_STATUS_GREEN_RED_ON	3

#define STC_MENU_WHITE_BALANCE_MODE_OFF			0
#define STC_MENU_WHITE_BALANCE_MODE_MANUAL		1
#define STC_MENU_WHITE_BALANCE_MODE_FULLAUTO	2
#define STC_MENU_WHITE_BALANCE_MODE_ONESHOT		3

#define STC_MENU_TRANSFER_BITS_PER_PIXEL_RAW_08				0
#define STC_MENU_TRANSFER_BITS_PER_PIXEL_RAW_10				1
#define STC_MENU_TRANSFER_BITS_PER_PIXEL_RAW_10P			2
#define STC_MENU_TRANSFER_BITS_PER_PIXEL_RAW_12				3
#define STC_MENU_TRANSFER_BITS_PER_PIXEL_RAW_12P			4
#define STC_MENU_TRANSFER_BITS_PER_PIXEL_MONO_08			5
#define STC_MENU_TRANSFER_BITS_PER_PIXEL_MONO_10			6
#define STC_MENU_TRANSFER_BITS_PER_PIXEL_MONO_10P			7
#define STC_MENU_TRANSFER_BITS_PER_PIXEL_MONO_12			8
#define STC_MENU_TRANSFER_BITS_PER_PIXEL_MONO_12P			9
#define STC_MENU_TRANSFER_BITS_PER_PIXEL_BGR_08				10
#define STC_MENU_TRANSFER_BITS_PER_PIXEL_BGR_10				11

#define STC_MENU_HDR_TYPE_NONE			0x0000
#define STC_MENU_HDR_TYPE_CMOSIS_4M		0x0001

#define STC_SIGNAL_CALLBACK_EXPOSURE_END		34
#define STC_SIGNAL_CALLBACK_TRANSFER_END		35
#define STC_SIGNAL_CALLBACK_ERROR				36

#define STC_ERROR_TIMEOUT_ST2EE 1
#define STC_ERROR_TIMEOUT_TE2EE 2
#define STC_ERROR_TIMEOUT_EE2TE 3
#define STC_ERROR_TIMEOUT_RO2TE 4

// Sentech original ioctl command
#define STC_IOC_PARAM_LEN_PRODUCT_NAME	32
#define STC_IOC_PARAM_LEN_USER_DATA		1024
#define STC_IOC_PARAM_LEN_CAMERA_NAME	250

#pragma pack(push,1)
struct stcam_st_cam_version {
	__u16	vendor_id;
	__u16	product_id;
	__u16	camera_type;
	__u8	product_name[STC_IOC_PARAM_LEN_PRODUCT_NAME];
	__u16	fpga_version;
	__u16	firm_version;
};

struct stcam_st_user_data {
	__u8	data[STC_IOC_PARAM_LEN_USER_DATA];
	__u16	offset;
	__u16	length;
};

struct stcam_st_cam_user_id {
	__u32	camera_id;
	__u8	camera_name[STC_IOC_PARAM_LEN_CAMERA_NAME];
	__u8	length;
};

struct stcam_st_max_scan_size {
	__u16	width;
	__u16	height;
};

struct stcam_st_scan_normal {
	__u16	offset_x;
	__u16	offset_y;
	__u16	width;
	__u16	height;
};

struct stcam_st_scan_roi {
	__u16	offset_x;
	__u16	offset_y;
	__u16	width;
	__u16	height;
	__u8	index;
	__u8	region_mode;
};

struct stcam_st_scan_size {
	union {
		struct stcam_st_scan_normal	normal;
		struct stcam_st_scan_roi	roi;
	};
};

struct stcam_st_hdr_cmosis_4m {
	__u8	mode;
	__u8	slope;
	__u8	vlow3;
	__u8	vlow2;
	__u8	knee2;
	__u8	knee1;
};

struct stcam_st_hdr {
	union {
		struct stcam_st_hdr_cmosis_4m	cmosis_4m;
	};
};

struct stcam_st_def_pix_correct_pos {
	__u8	index;
	__u16	pos_x;
	__u16	pos_y;
};

#pragma pack(pop)

#define STCIOC_G_CAM_VERSION			_IOR('V',	BASE_VIDIOC_PRIVATE + 0,	struct stcam_st_cam_version)
#define STCIOC_G_USER_DATA				_IOR('V',	BASE_VIDIOC_PRIVATE + 1,	struct stcam_st_user_data)
#define STCIOC_S_USER_DATA				_IOW('V',	BASE_VIDIOC_PRIVATE + 2,	struct stcam_st_user_data)
#define STCIOC_G_CAM_USER_ID			_IOR('V',	BASE_VIDIOC_PRIVATE + 3,	struct stcam_st_cam_user_id)
#define STCIOC_S_CAM_USER_ID			_IOW('V',	BASE_VIDIOC_PRIVATE + 4,	struct stcam_st_cam_user_id)
#define STCIOC_G_MAX_SCAN_SIZE			_IOR('V',	BASE_VIDIOC_PRIVATE + 5,	struct stcam_st_max_scan_size)
#define STCIOC_G_SCAN_SIZE				_IOWR('V',	BASE_VIDIOC_PRIVATE + 6,	struct stcam_st_scan_size)
#define STCIOC_S_SCAN_SIZE				_IOW('V',	BASE_VIDIOC_PRIVATE + 7,	struct stcam_st_scan_size)
#define STCIOC_G_HDR					_IOR('V',	BASE_VIDIOC_PRIVATE + 8,	struct stcam_st_hdr)
#define STCIOC_S_HDR					_IOW('V',	BASE_VIDIOC_PRIVATE + 9,	struct stcam_st_hdr)
#define STCIOC_G_DEF_PIX_CORRECT_POS	_IOR('V',	BASE_VIDIOC_PRIVATE + 10,	struct stcam_st_def_pix_correct_pos)
#define STCIOC_S_DEF_PIX_CORRECT_POS	_IOW('V',	BASE_VIDIOC_PRIVATE + 11,	struct stcam_st_def_pix_correct_pos)

#endif//__STCAM_DD_H__
